#! /usr/bin/env bash

function install-dir () {
  local dir="${1:?Missing directory}"

  echo pip install -r "$dir/requirements.txt" -t ./src/vendor --upgrade
  pip install -r "$dir/requirements.txt" -t ./src/vendor --upgrade
}


install-dir ./src
install-dir ./functions/custom_resources
install-dir ./functions/TenantManagementService
install-dir ./functions/Resources